version: '3.8' # Docker Compose 的版本
services:
  redis:
    image: redis:6-alpine
    container_name: ai-redis
    ports:
      - "6379:6379"
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-worker
    # 修正啟動命令，確保 Python 路徑包含專案根目錄
    command: python -m worker.worker
    volumes:
      - ./tasks:/app/tasks
      - ./worker:/app/worker
    depends_on:
      - redis
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./tasks:/app/tasks
    depends_on:
      - redis
    restart: on-failure